### ISSUE TITLE
Need to check ThrowableListener class is used to get the error during the server startup or not

### ISSUE THREAD

**Issue by kalaiyarasiganeshalingam** [wso2-ballerina/module-sap#4]
**Description:**
https://github.com/wso2-ballerina/module-sap/pull/2/files/8f701c8486997363f8f0a87f444de47dd5a620da#r292738114

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by anupama-pathirage** [comment]
Closing as we are no longer maintaining this code.
